### PR TITLE
fix: manual and map address input on placeorder

### PR DESCRIPTION
**Pull request by ardiankristo**
Proof of work:
Screenshot from 2022-12-21 10-56-29
Screenshot from 2022-12-21 10-56-33
Screenshot from 2022-12-21 13-06-43
Screenshot from 2022-12-21 13-06-46
Screenshot from 2022-12-21 13-07-21
Screenshot from 2022-12-21 13-10-34
Screenshot from 2022-12-21 13-10-38
Screenshot from 2022-12-21 13-11-44
Screenshot from 2022-12-21 13-11-53
Screenshot from 2022-12-21 13-12-04
Screenshot from 2022-12-21 13-12-11
Screenshot from 2022-12-21 13-12-28

Account:
Screenshot from 2022-12-21 13-13-00

Shipping Method:
Screenshot from 2022-12-21 13-13-40

Tab (max 575px, if more than 575px then max width is set to 375px) :
Screenshot from 2022-12-21 13-14-19
Screenshot from 2022-12-21 13-16-15
Screenshot from 2022-12-21 13-16-19
Screenshot from 2022-12-21 13-16-27
Screenshot from 2022-12-21 13-19-25

### CODE REVIEW

**Comment by feliciakri** [comment]
untuk yang pilihan alamat dan negara itu 
image
image
kira-kira spacing nya bisa diratain ga ya? apa emang limited untuk styling nya?

kalo di figmanya rata soalnya
image

**Review by sultanfariz — APPROVED** [review]

**Comment by DiebrataA** [comment]
untuk bagian warna hover opsi alamat dan active border untuk input alamatnya sepertinya warnanya berbeda dengan design figma mas
Screenshot from 2022-12-21 13-12-04

ini yang dari Figma
image

**Comment by ardiankristo** [comment]
Screenshot from 2022-12-22 09-28-48
Screenshot from 2022-12-22 09-30-27
Screenshot from 2022-12-22 09-30-31

**Comment by feliciakri** [comment]
yang ini gabisa ya mas? 
image

**Review by DiebrataA — APPROVED** [review]

**Comment by ardiankristo** [comment]
Screenshot from 2022-12-22 11-05-37

**Review by feliciakri — APPROVED** [review]

**Pull request merged**
